<?php

/**
 * Implements hook_theme().
 */
function module2_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'greet_theme' => [
      'render element' => 'children',
      'template' => 'module2-template',
      'path' => $path . '/templates',
      'variables' => [
        'name' => 'NA'
      ],
    ],
  ];

}
